spec:
  alerts:
  - rules: DEPLOYMENT_FAILED
  - rules: DOMAIN_FAILED
  workers:
  - github:
      branch: main
      deploy_on_push: true
      repo: digitalocean/golang-slackbot
    name: slackbot-api
    source_dir: /
  name: slackbot
